#!/bin/bash

yum -y install squid httpd-tools
sed -i "s/http_access deny all/http_access allow all/" /etc/squid/squid.conf
sed -i "s/http_port 3128/http_port 34567/" /etc/squid/squid.conf
sed -i "$ a  error_directory /usr/share/squid/errors/ja" /etc/squid/squid.conf
sed -i "$ a  forwarded_for off" /etc/squid/squid.conf
sed -i "$ a  request_header_access X-Forwarded-For deny all" /etc/squid/squid.conf
sed -i "$ a  request_header_access Via deny all" /etc/squid/squid.conf
sed -i "$ a  request_header_access Cache-Control deny all" /etc/squid/squid.conf
systemctl enable squid
systemctl start squid

if[ ! -e /var/spool/cron/root];
  touch /var/spool/cron/root
fi
sed -i '$ a 0 11,23 * * * /usr/sbin/reboot' /var/spool/cron/root
