#!/bin/bash

yum -y install squid httpd-tools
sed -i "s/http_access deny all/#http_access deny all/" /etc/squid/squid.conf
sed -i "s/http_port 3128/http_port 34567/" /etc/squid/squid.conf
sed -i "$ a  error_directory /usr/share/squid/errors/ja" /etc/squid/squid.conf
sed -i "$ a  forwarded_for off" /etc/squid/squid.conf
sed -i "$ a  request_header_access X-Forwarded-For deny all" /etc/squid/squid.conf
sed -i "$ a  request_header_access Via deny all" /etc/squid/squid.conf
sed -i "$ a  request_header_access Cache-Control deny all" /etc/squid/squid.conf

sed -i "$ a  auth_param basic program /lib64/squid/basic_ncsa_auth /etc/squid/pass" /etc/squid/squid.conf
sed -i "$ a  auth_param basic realm proxy" /etc/squid/squid.conf
sed -i "$ a  acl authenticated proxy_auth REQUIRED" /etc/squid/squid.conf
sed -i "$ a  acl friday time F 0:00-24:00" /etc/squid/squid.conf
sed -i "$ a  acl saturday time A 0:00-24:00" /etc/squid/squid.conf
sed -i "$ a  http_access allow authenticated friday" /etc/squid/squid.conf
sed -i "$ a  http_access allow authenticated saturday" /etc/squid/squid.conf
sed -i "$ a  http_access deny all" /etc/squid/squid.conf
systemctl enable squid
systemctl start squid
firewall-cmd --zone=public --add-port=34567/tcp --permanent
firewall-cmd --reload
htpasswd -c -i -b /etc/squid/pass week13 tezlpr0mpt
